spring:
  config:
    activate:
      on-profile: "actuator"
management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /heroes-actuator
    jmx:
      exposure:
        exclude: "*"
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
