name: Code Style Check
on:
#  pull_request:
#    branches:
#      - develop
  push:
    branches:
      - fix/#47-deploy-fix
jobs:
  style-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Apply Spotless
        run: |
          ./gradlew spotlessApply

      - name: Checkstyle
        run: |
          ./gradlew spotlessCheck

      - name: Check if there are changes
        id: check_changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Changes detected"
            echo "CHANGES_DETECTED=true" >> $GITHUB_ENV
          else
            echo "No changes"
            echo "CHANGES_DETECTED=false" >> $GITHUB_ENV
          fi

      - name: Commit and Push changes if any
        if: env.CHANGES_DETECTED == 'true'
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add .
          git commit -m "Apply Spotless fixes"
          git remote set-url origin https://x-access-token:${{ secrets.HEROES_TOKEN }}@github.com/${{ github.repository }}
          git push origin HEAD:${{ github.ref }}
#          git push origin HEAD:${{ github.event.pull_request.head.ref }}

