name: Deploy to Elastic Beanstalk

on:
  push:
    branches: [ "chore/#4-fix-eb-setting" ]

env:
  DOCKERHUB_IMAGE_NAME: heroes-server
  EXISTING_BUCKET_NAME: "elasticbeanstalk-ap-northeast-2-381492252208"
  APPLICATION_NAME: "server"
  ENVIRONMENT_NAME: "Server-env-1"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: prod
    strategy:
      matrix:
        java-version: [ 17 ]
        distribution: [ 'zulu' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.distribution }}

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        id: gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: |
            build
            --scan
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop' }}

      - name: Docker build & push
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_IMAGE_NAME }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_IMAGE_NAME }}

      - name: Current Time
        uses: gerred/current-time@v1.0.0
        id: current-time

      - name: Replace string
        uses: frabert/replace-string-action@v2.1
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'

      - name: Prepare deployment package
        run: |
          zip -r deployment-package.zip docker-compose.yml nginx/default.conf

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          existing_bucket_name: ${{ env.EXISTING_BUCKET_NAME }}
          application_name: ${{ env.APPLICATION_NAME }}
          environment_name: ${{ env.ENVIRONMENT_NAME }}
          version_label: "heroes-dev-${{ steps.format-time.outputs.replaced }}"
          region: ap-northeast-2
          deployment_package: deployment-package.zip
          wait_for_environment_recovery: 180

